### ISSUE TITLE
Wrapping MaterialUI components

### ISSUE THREAD

**Issue by timjs** [purescript-concur/purescript-concur-react#27]
Really like the ideas behind Concur, and I'd like to experiment with some predefined component library! I see that [the semantic wrapper](https://github.com/ajnsit/purescript-concur-semantic) is ongoing work/stalled. Any idea how difficult it would be to wrap an existing PureScript library like [React MUI](https://github.com/doolse/purescript-react-mui) or [React Material UI](https://github.com/nwolverson/purescript-react-material-ui) instead of creating bindings to Semantic UI from scratch?

**Comment by ajnsit** [comment]
The Semantic UI Wrapper uses the old Concur API and is not really usable anymore. I have archived that repo now. The new API actually makes it really simple to work with external components in Concur so the amount of work required to roll your own is significanlty smaller.

Adding new bindings for MUI based on the existing purescript library seems like a good idea! I will explore that.

**Comment by kamoii** [comment]
@ajnsit Hi, I'm intrested in how embedding external components in concur code will look like. Is there any sample how to work with external components?

>  The new API actually makes it really simple to work with external components in Concur so the amount of work required to roll your own is significanlty smaller.

**Comment by ajnsit** [comment]
@kamoii Usually all you would require to wrap an external component is to import it as a `ReactClass`, and then wrapping it with one of the `el` functions.

For example, let's say you want to wrap the `Button` component provided by the material-ui library.

*Step 1*: First write an FFI module that exposes the `ReactClass` component -

```javascript
// Button.js
exports.classButton =  require('@material-ui/core/Button').default
```

And import it into your purescript program

```purescript
-- Button.purs
foreign import classButton :: forall a. ReactClass a
```

If you are using the [Purescript React MUI bindings](https://github.com/doolse/purescript-react-mui), then you can simply import the class component from the library without defining the FFI module -

```purescript
import MaterialUI.Button (classButton)
```

An aside: The MUI bindings also provide Props type definitions for components, but we don't use them. This is because I am yet to figure out a nice API for typesafe props for components. By "typesafe", I mean ensuring at compile time that you are not passing a prop to a button that is not a part of the allowed set of props for buttons. In practice, I have found that it's not very useful since lots of react props can be used for a large number of components, and it would be a lot of work to map them properly.

*Step 2*: Then wrap up the imported `ReactClass` into a widget to make it usable within Concur -

```purescript
import Concur.React.DOM (El, el')
import React (unsafeCreateElement)
import React.DOM.Props (unsafeFromPropsArray)

button :: El
button = el' (unsafeCreateElement classButton <<< unsafeFromPropsArray)
```

(Ignore the `unsafe` functions. That's basically the cost of not having typesafe props. It's on my todo list).

*Step 3*: Now you can use `button` normally within Concur. For example -

```purescript
import Concur.React.DOM as D
import Concur.React.Props as P

helloButton = button [P.onClick] [D.text "Hello World!"]
```

Note that you can mix in the default widgets and props with the MUI ones.

**Comment by kamoii** [comment]
@ajnsit Thank you for your detailed explanation :+1: 
I will try it.

**Comment by ajnsit** [comment]
I started a new project for MUI bindings here - https://github.com/ajnsit/purescript-concur-react-mui. To try run -

```sh
npm install
cd examples
npx spago build
npx parcel index.html
```
