### ISSUE TITLE
Best design for nested/"local" state

### ISSUE THREAD

**Issue by seven7e** [purescript-concur/purescript-concur-react#62]
I'm implementing a page contains two tabs A and B, where A contains a component changing every second (take a clock as example), and B is static. Naturally there are two buttons switching the tabs.

My question is, is it possible to keep the state of tab A locally? i.e. the clock inside tab A is managed by itself, and the tab component are not aware of the contents inside the tabs. From the viewpoint of the tabs widget, the content of each tab is just passed as `Widget HTML a`. And I need to keep the state of the clock when the tab is not active, i.e. if I switch to tab B and back to A, the clock is not restarted from its initial state.

I understand that I can put all states (current tab, clock state) at top level (kind of elm-like architecture), but just wondering if there's a way to have "internal" states for a Widget so that the outer widget is not aware of what kind of widgets inside it? Thanks.

**Comment by ajnsit** [comment]
This is a couple of years too late, but I'm working on Concur again and trying to work through the reported issues.

Since widgets can perform effects, you can use Refs to store local state. I just added an ergonomic function that helps do just that! Check out `Concur.Core.Patterns.internalise` - https://github.com/purescript-concur/purescript-concur-core/commit/cdd2a0f7e8b5d377bc6097be9084f5f89b888370

I also added an example of tabs with persisting local state - https://github.com/purescript-concur/purescript-concur-react/commit/f28b51c135660a10e36bafd685af1b401897b4a4

HTH!
